name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set environment
      id: environment
      run: |
        echo ${{ github.event_name }}
        if [[ ${{ github.event_name == "release" }} ]]; then
          tag=prod
        else
          tag=staging
        fi
        echo "::set-output name=environment::${tag}"

   - name: Set new variable value
      id: tags
      run: |
        echo "${{ steps.environment.outputs.environment }}"